config/routes.rb
Rails.application.routes.draw do
  resources :texts
  devise_for :users
  resources :notes

  scope(path_names: { new: "add" }) do
    resources :links, path: "news"
  end

  root "home#index" # to: redirect("/news")
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  url        :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Link < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true

  def host
    URI(url).host.sub("www.", "")
  end

  def crawl
    page = MetaInspector.new(url)
    self.title = page.best_title
    self.body = page.description
    self.created_at = Time.zone.now
  end

  def to_param
    [created_at.strftime("%F"), title.parameterize, id].join("-")
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit create update destroy]

  before_action do
    set_meta_tags site: "Hākuturi News"
  end

  def index
    @query = params[:q].presence
    page = (params[:page] || "1").to_i
    limit = (params[:limit] || "10").to_i
    scope = @query ? Link.basic_search(@query) : Link.all
    @links = scope.order(created_at: :desc).page(page).per(limit)
  end

  def show
    redirect_to(@link, status: 301) if @link.to_param != params[:id]
  end

  def new
    @link = Link.new
    authorize @link
  end

  def edit
    authorize @link
  end

  def create
    @link = Link.new(link_params)
    authorize @link

    respond_to do |format|
      if @link.url.present? && params[:commit] == "Crawl"
        @link.crawl
        format.html { render :new }
      elsif @link.save
        format.html { redirect_to links_path, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @link
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to links_path, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @link
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_link
    @link = Link.find(params[:id].split("-").last)
  end

  def link_params
    params.require(:link).permit(:title, :url, :body, :created_at)
  end
end

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h4>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.url_field :url, id: :link_url, class: "form-control", placeholder: "https://www.example.com" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :link_title, class: "form-control", placeholder: "title of the link" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :link_body, class: "form-control", style: "height:15rem", placeholder: "summary of the link" %>
  </div>

  <div class="form-group">
    <%= form.label :created_at %>
    <%= form.datetime_field :created_at, id: :link_created_at, class: "form-control", placeholder: "YYYY-MM-DDThh:mm:ss" %>
  </div>

  <div class="mt-4">
    <%= form.submit class: "btn btn-primary" %>
    <%= form.submit "Crawl", class: "btn btn-outline-primary ml-3" %>
  </div>
<% end %>

app/views/links/_header.html.erb
<%= content_for :header_title do %>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to root_path, itemprop: "item" do %><span itemprop="name">Hākuturi</span><% end %>
    <meta itemprop="position" content="1" />
  </li>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to links_path, itemprop: "item" do %><span itemprop="name">News</span><% end %>
    <meta itemprop="position" content="2" />
  </li>
<% end %>

app/views/links/_link.html.erb
<article class="card" itemscope itemtype="http://schema.org/Article">
  <div class="card-header">
    <div class="row text-muted">
      <div class="col col-auto" itemprop="publisher" itemtype="https://schema.org/Organization" itemscope="itemscope">
        <span itemprop="name"><%= link.host %></span>
      </div>
      <div class="col text-right">
        <%= link_to(link, class: "text-muted") do %>
          <%= time_tag(link.created_at, time_ago_in_words(link.created_at), itemprop: "datePublished") %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-body">
    <h1 class="card-title h5 mb-0"><%= link_to link.title, link.url %></h1>

    <% if link.body.present? %>
      <div class="card-text mt-3" itemprop="headline">
        <%= markdown_format link.body %>
      </div>
    <% end %>

    <% if policy(link).update? %>
      <div class="mt-3">
        <a href="http://twitter.com/share?url=<%=u link.url %>&text=<%=u link.title %>" target="_blank" class="btn btn-primary float-right ml-2" role="button">Tweet</a>

        <%= link_to "Edit", edit_link_path(link), class: "btn btn-primary", role: "button" %>
        <%= link_to "Delete", link_path(link), class: "btn btn-outline-danger ml-2", role: "button", data: { confirm: "Are you sure?" }, method: :delete %>
      </div>
    <% end %>
  </div>
</article>

app/views/links/_links.html.erb
<% links.each do |link| %>
  <%= render "link", link: link %>
<% end %>

app/views/links/edit.html.erb
<%= render "header" %>

<h1>Edit News</h1>

<%= render 'form', link: @link %>

app/views/links/index.html.erb
<%= render "header" %>

<% description "Hākuturi News is a curated news aggregator focused on the environment" %>

<% if policy(@links).create? %>
  <div class="text-center mb-4">
    <%= link_to "Add News", new_link_path, class: "btn btn-primary", role: "button" %>
  </div>
<% end %>

<aside class="search mb-4">
  <form action="/news" accept-charset="UTF-8" method="get">
    <div class="input-group">
      <input type="search" name="q" id="q" value="<%= @query %>" placeholder="Search the news" class="form-control border-right-0" aria-label="Query" />
      <span class="input-group-append bg-white">
        <button class="btn btn-outline-primary" id="search-submit" aria-label="Search">
          <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </form>
</aside>

<% if @links.present? %>
  <div id="links">
    <%= render "links", links: @links %>
  </div>

  <% unless @links.last_page? %>
    <div class="next-page text-center mt-4">
      <%= link_to_next_page @links, "Next Page", remote: true, class: "btn btn-primary", role: "button" %>
    </div>
  <% end %>
<% elsif @query.present? %>
  <p>No results found for "<strong><%= @query %></strong>".</p>
<% end %>

app/views/links/index.js.erb
// Append new data
$("<%=j render(partial: "links/links", :object => @links) %>").appendTo($('#links'));

// Update next-page link
<% if @links.last_page? %>
  $('.next-page').html('');
<% else %>
  $('.next-page').html("<%=j link_to_next_page @links, "Next Page", remote: true, class: "btn btn-primary", role: "button" %>");
<% end %>

app/views/links/new.html.erb
<%= render "header" %>

<h1>Add News</h1>

<%= render 'form', link: @link %>

app/views/links/show.html.erb
<%= render "header" %>

<% title @link.title %>
<% description @link.body %>

<%= render "link", link: @link %>

<div class="text-center mt-4">
  <%= link_to "More News", links_path, class: "btn btn-primary", role: "button" %>
</div>