config/routes.rb
Rails.application.routes.draw do
  resources :texts
  devise_for :users
  resources :notes

  scope(path_names: { new: "add" }) do
    resources :links, path: "news"
  end

  root "home#index" # to: redirect("/news")
end

app/models/text.rb
# == Schema Information
#
# Table name: texts
#
#  id           :bigint(8)        not null, primary key
#  title        :string
#  author       :string
#  body         :text
#  published_on :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Text < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :body, presence: true
  validates :published_on, presence: true

  def to_param
    [published_on.strftime("%Y"), title.parameterize, id].join("-")
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  include TextsHelper

  before_action :set_text, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit create update destroy]

  before_action do
    set_meta_tags site: "Hākuturi Texts"
  end

  def index
    page = (params[:page] || "1").to_i
    limit = (params[:limit] || "20").to_i
    @texts = Text.all.order(published_on: :desc).page(page).per(limit)
  end

  def show
    redirect_to(@text, status: 301) if @text.to_param != params[:id]

    respond_to do |format|
      format.html
      format.text
      format.epub do
        send_data(render_epub(@text), filename: "#{@text.id}.epub", type: "application/epub")
      end
    end
  end

  def new
    @text = Text.new
    authorize @text
  end

  def edit
    authorize @text
  end

  def create
    @text = Text.new(text_params)
    authorize @text

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: "Text was successfully created." }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @text
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: "Text was successfully updated." }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @text
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: "Text was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_text
    @text = Text.find(params[:id].split("-").last)
  end

  def text_params
    params.require(:text).permit(:title, :author, :body, :source, :published_on)
  end
end

app/helpers/texts_helper.rb
module TextsHelper
  class CustomRender < Redcarpet::Render::HTML
    # include Redcarpet::Render::SmartyPants
    def preprocess(doc)
      doc.gsub("---", "&mdash;").gsub("--", "&ndash;")
    end
  end

  def markdown_format(source)
    markdown = Redcarpet::Markdown.new(CustomRender)
    markdown.render(source).html_safe
  end

  def render_epub(text)
    lang = "en"
    html = <<~HTML
      <?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE html>
      <html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="#{lang}" lang="#{lang}">
        <head>
          <meta content="charset=utf-8"/>
          <title>#{text.title}</title>
        </head>
        <body>
          <h2 style="text-align:center">#{text.author} (#{text.published_on.year})</h2>
          <h1 style="text-align:center">#{text.title}</h1>
          #{markdown_format(text.body)}
        </body>
      </html>
    HTML

    # Markdown conversion may produce HTML entities that are not valid XHTML
    doc = Nokogiri::XML.parse(html)
    xhtml = doc.to_xhtml(indent: 2, encoding: "UTF-8")

    gbook = GEPUB::Book.new do |book|
      book.identifier = text_url(text)
      book.title = text.title
      book.creator = text.author
      book.language = lang

      book.ordered do
        item = book.add_item("content.xhtml")
        item.add_content(StringIO.new(xhtml))
      end
    end

    gbook.generate_epub_stream.string
  end
end

app/views/texts/_form.html.erb
<%= form_with(model: text, local: true) do |form| %>
  <% if text.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h4>

      <ul>
      <% text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "title of the text" %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: "form-control", placeholder: "author of the text" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", style: "height:21rem", placeholder: "body of the text" %>
  </div>

  <div class="form-group">
    <%= form.label :source %>
    <%= form.text_area :source, class: "form-control", style: "height:6rem", placeholder: "source of the text" %>
  </div>

  <div class="form-group">
    <%= form.label :published_on %>
    <%= form.date_field :published_on, class: "form-control", placeholder: "YYYY-MM-DD" %>
  </div>

  <div class="mt-4">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/texts/_header.html.erb
<%= content_for :header_title do %>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to root_path, itemprop: "item" do %><span itemprop="name">Hākuturi</span><% end %>
    <meta itemprop="position" content="1" />
  </li>
  <li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <%= link_to texts_path, itemprop: "item" do %><span itemprop="name">Texts</span><% end %>
    <meta itemprop="position" content="2" />
  </li>
<% end %>

app/views/texts/_texts.html.erb
<% texts.each do |text| %>
  <li>
    <%= link_to "#{text.title}", text %>
    <span class="text-muted"> - <%= text.author %> (<%= text.published_on.year %>)</span>
  </li>
<% end %>

app/views/texts/edit.html.erb
<%= render "header" %>

<h1>Edit Text</h1>

<%= render 'form', text: @text %>

app/views/texts/index.html.erb
<%= render "header" %>

<% description "Hākuturi Texts is collection of resources to understand our modern societies" %>

<% if policy(@texts).create? %>
  <div class="text-center mb-4">
    <%= link_to "Add Text", new_text_path, class: "btn btn-primary", role: "button" %>
  </div>
<% end %>

<% if @texts %>
  <ul id="texts">
    <%= render "texts", texts: @texts %>
  </ul>

  <% unless @texts.last_page? %>
    <div class="next-page text-center mt-4">
      <%= link_to_next_page @texts, "Next Page", remote: true, class: "btn btn-primary", role: "button" %>
    </div>
  <% end %>
<% end %>

app/views/texts/new.html.erb
<%= render "header" %>

<h1>Add Text</h1>

<%= render 'form', text: @text %>

app/views/texts/show.html.erb
<%= render "header" %>

<header class="pb-2">
  <p class="h3 text-center text-muted"><%= @text.author %> (<%= @text.published_on.year %>)</p>
  <h1 class="text-center my-3"><%= title @text.title %></h1>
</header>

<% if policy(@text).update? %>
  <div class="btn-toolbar-admin mb-4">
    <%= link_to "Edit", edit_text_path(@text), class: "btn btn-primary", role: "button" %>
    <%= link_to "Delete", text_path(@text), class: "btn btn-outline-danger ml-2", role: "button", data: { confirm: "Are you sure?" }, method: :delete %>
  </div>
<% end %>

<article>
  <%= markdown_format @text.body %>
</article>

<% if @text.source.present? %>
  <div class="alert alert-secondary mt-4" role="alert">
    <%= markdown_format @text.source %>
  </div>
<% end %>

<div class="text-center mt-4">
  <%= link_to "More Texts", texts_path, class: "btn btn-primary", role: "button" %>
</div>

app/views/texts/show.text.erb
# <%= @text.title %> (<%= @text.author %>, <%= @text.published_on.year %>)

<%= @text.body %>