config/routes.rb
Rails.application.routes.draw do
  resources :texts
  devise_for :users
  resources :notes

  scope(path_names: { new: "add" }) do
    resources :links, path: "news"
  end

  root "home#index" # to: redirect("/news")
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-xl navbar-inverse bg-primary <%= content_for(:page) == 'home' ? '' : 'mb-3' %>">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% unless content_for(:page) == 'home' %>
    <a class="navbar-brand" href="/">Hākuturi</a>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= page_meta_tags %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body class="d-flex flex-column <%= controller_name %>">
    <% if controller_name == "home" %>
      <header class="p-4 fullscreen d-flex flex-column text-white-90 text-shadow">
        <%= video_tag("background.mp4", poster: "background.jpg", class: "background-video", playsinline: true, autoplay: true, muted: true, loop: true,) %>
        <nav class="justify-self-start text-right flex-grow-1">
          <%= link_to "News", links_path %>
          <% if current_user&.admin? %>
            <%= link_to "Texts", texts_path, class: "ml-3" %>
          <% end %>
        </nav>

        <div class="container">
          <%= content_for :header_title %>
        </div>
      </header>
    <% else %>
      <header class="p-4 text-white-90 text-shadow">
        <%= image_tag("background.jpg", class: "background-video") %>
        <ol itemscope itemtype="https://schema.org/BreadcrumbList" class="text-center display-4 m-0">
          <%= content_for :header_title %>
        </ol>
      </header>

      <main class="flex-grow-1">
        <div class="container p-4">
          <% if alert %>
            <div class="alert alert-danger" role="alert"><%= alert %></div>
          <% end %>
          <% if notice %>
            <div class="alert alert-success" role="alert"><%= notice %></div>
          <% end %>

          <%= yield %>
        </div>
      </main>
    <% end %>
  </body>
</html>